### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by dfeyer** [Plume-org/docs#2]
- [ ] Review the docker-compose setup
- [ ] Plume require HTTPS connection (see https://github.com/Plume-org/Plume/issues/412)

**Comment by trinity-1686a** [comment]
I think instead of providing an half working http (no s) option, we should link to/write something about how to setup a local CA to test things

**Comment by DeadSuperHero** [comment]
Any progress on this? This issue prevents me from actually using Plume for local testing purposes.

**Comment by elegaanz** [comment]
I didn't reviewed the docker-compose files, but I updated [the development guide with instructions for HTTPS](https://docs.joinplu.me/development/).

**Comment by elegaanz** [comment]
I think the docker-compose files are now OK with the latest commit.
