### ISSUE TITLE
Document development setup

### ISSUE THREAD

**Issue by elegaanz** [Plume-org/docs#3]
Especially how to setup HTTPS (I think [Caddy](https://caddyserver.com/) and [mkcert](https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/) is the way to go (we need mkcert since caddy uses self signed certificates for local sites, which are rejected when federating))

**Comment by igalic** [comment]
I've been using [mod_md](https://httpd.apache.org/docs/trunk/mod/mod_md.html) and it as quite easy too! compared to the usual ceremony…

**Comment by elegaanz** [comment]
I added explanations about Caddy, but if you want to document what you are doing with mod_md, @igalic feel free to do so!
