### ISSUE TITLE
Say that there are pre-built docker images

### ISSUE THREAD

**Issue by elegaanz** [Plume-org/docs#4]
Thanks to  @mcrosson there are pre-built images available at https://docker.lollipopcloud.solutions/. I think most people will prefer to use them instead of building them manually, so we should probably mention that in the installation docs.

**Comment by igalic** [comment]
can they also be pulled from docker hub?
*********
yesno! Lollipop Cloud has their own hub.
But it would be good to have some presence at [hub.docker.com](https://hub.docker.com/search?q=plume&type=image)

**Comment by mcrosson** [comment]
@igalic I'm not publishing the lollipop cloud builds to docker hub at all.

If @BaptisteGelez creates an organization for Plume I can work with them or other project members to start setting up builds + deployments of the x86-64 version of Plume -> docker hub.

**Comment by igalic** [comment]
oh yes please!

**Comment by elegaanz** [comment]
The sample docker-compose file now uses the prebuilt images. Thanks again for building them @mcrosson!
