### ISSUE TITLE
Command errors in documentation

### ISSUE THREAD

**Issue by papey** [Plume-org/docs#51]
Documentation says :

> plm migration run

But this is not a [valid command](https://github.com/Plume-org/Plume/blob/0.3.0-alpha-2/plume-cli/src/main.rs) in 0.0.3-alpha-2 release.

See [this thread](https://toots.benpro.fr/@benoit/102359466236998527) for a real life exemple

**Comment by BlueRaccoonTech** [comment]
I ran into this same issue trying to set up a Plume instance. I wound up resolving it for myself by running `diesel database setup`, which seemed to be what was instructed to be run prior.

**Comment by elegaanz** [comment]
Indeed, `plm migration` was added after the 0.3.0 release, we updated the "stable" docs too fast. Sorry, it should be fixed now.
