### ISSUE TITLE
Documentation doesn't mention ROCKET_ADDRESS

### ISSUE THREAD

**Issue by asonix** [Plume-org/docs#57]
When setting up Plume, I found I couldn't access my instance when visiting the URL I had set up, this was because Plume wasn't running on the same host as the Reverse Proxy, and it had bound to localhost:7878 and not [my host's ip]:7878. I found the `env("ROCKET_ADDRESS")` when looking through the source code and got it set up properly, but not everyone will be able to read Rust code.

**Comment by trinity-1686a** [comment]
(I've transferred this issue to the right repository)
`ROCKET_ADDRESS` is mentioned [here](https://docs.joinplu.me/environment/), and this page is linked just under the sample `.env` that is given as an installation step [here](https://docs.joinplu.me/installation/config). Do you know what we could do to make it standout more (rephrasing, different formatting...) ?

**Comment by asonix** [comment]
ah, I missed that link entirely
