### ISSUE TITLE
Broken CSS

### ISSUE THREAD

**Issue by tastytea** [Plume-org/docs#8]
There is no default text color specified. To reproduce, configure your browser to use white text on black
background as fallback.

![screenshot_2019-02-18t01 24 23](https://user-images.githubusercontent.com/3681516/52921880-9e047c00-3313-11e9-89b6-f79e602ffc7e.png)

See also: https://github.com/Plume-org/joinplu.me/issues/4

**Comment by elegaanz** [comment]
Sorry, I should really remember to always define a default text color…
